// ============================================================
// 球队档案 — 阵容 · 战术 · 状态 · 伤员
// ============================================================

const TeamProfiles = {
  // ── A 组 ──
  MEX: {
    coach:'哈维尔·阿吉雷', coachStyle:'务实型', formation:'4-3-3',
    playStyle:['快速反击','边路进攻','高位逼抢'],
    strengths:['主场优势','球迷狂热','速度型球员多'], weaknesses:['中场控制力一般','大赛关键时刻掉链子'],
    keyPlayers:[{ name:'洛萨诺',pos:'LW',rating:78,status:'fit' },{ name:'吉梅内斯',pos:'ST',rating:77,status:'fit' },{ name:'阿尔瓦雷斯',pos:'CM',rating:76,status:'fit' }],
    injured:[], suspended:[], squadDepth:7, tournamentExp:7, morale:9, recentForm:['W','W','D','W','L'], fatigue:2,
    tacticalNotes:'东道主之一，阿吉雷的墨西哥会利用主场气氛和高海拔优势，打法直接快速。',
  },
  RSA: {
    coach:'雨果·布鲁斯', coachStyle:'务实型', formation:'4-4-2',
    playStyle:['身体对抗','快速反击','边路传中'],
    strengths:['身体素质出色','团队纪律'], weaknesses:['技术粗糙','创造力不足'],
    keyPlayers:[{ name:'陶·恩比恩耶马',pos:'CM',rating:72,status:'fit' },{ name:'Zwane',pos:'LW',rating:70,status:'fit' }],
    injured:[], suspended:[], squadDepth:5, tournamentExp:4, morale:6, recentForm:['L','D','W','L','D'], fatigue:2,
    tacticalNotes:'南非以身体对抗和纪律性见长，进攻端依赖边路传中和个人突破。',
  },
  KOR: {
    coach:'洪明甫', coachStyle:'务实型', formation:'4-2-3-1',
    playStyle:['高位逼抢','快速传递','团队配合'],
    strengths:['战术执行力强','体能充沛','团队纪律'], weaknesses:['身体对抗不足','高空球劣势'],
    keyPlayers:[{ name:'孙兴慜',pos:'LW',rating:87,status:'fit' },{ name:'黄仁范',pos:'CM',rating:76,status:'fit' },{ name:'金玟哉',pos:'CB',rating:82,status:'fit' }],
    injured:[], suspended:[], squadDepth:7, tournamentExp:7, morale:8, recentForm:['W','D','W','W','L'], fatigue:2,
    tacticalNotes:'洪明甫的韩国以高位逼抢和快速传递为核心，孙兴慜是绝对核心，整体移动能力极强。',
  },
  CZE: {
    coach:'伊万·哈谢克', coachStyle:'平衡型', formation:'4-2-3-1',
    playStyle:['控球型','中场压迫','技术流'],
    strengths:['中场技术出色','团队配合默契'], weaknesses:['锋线效率不稳','后防空当较大'],
    keyPlayers:[{ name:'绍切克',pos:'CM',rating:82,status:'fit' },{ name:'希克',pos:'ST',rating:78,status:'fit' },{ name:'科瓦尔',pos:'CB',rating:76,status:'fit' }],
    injured:[], suspended:[], squadDepth:6, tournamentExp:5, morale:6, recentForm:['D','W','L','W','D'], fatigue:2,
    tacticalNotes:'捷克延续东欧技术流传统，绍切克的中场统治力是关键，整体组织能力强。',
  },

  // ── B 组 ──
  CAN: {
    coach:'杰西·马什', coachStyle:'进攻型', formation:'4-3-3',
    playStyle:['高位逼抢','快速反击','边路突破'],
    strengths:['体能充沛','速度型球员多','主场气氛'], weaknesses:['大赛经验不足','关键时刻失误多'],
    keyPlayers:[{ name:'阿方索·戴维斯',pos:'LW',rating:84,status:'fit' },{ name:'大卫',pos:'ST',rating:79,status:'fit' },{ name:'布坎南',pos:'RW',rating:74,status:'fit' }],
    injured:[], suspended:[], squadDepth:6, tournamentExp:4, morale:7, recentForm:['W','D','L','W','D'], fatigue:2,
    tacticalNotes:'马什的加拿大以速度和体能见长，阿方索·戴维斯是绝对核心，东道主之一。',
  },
  BIH: {
    coach:'谢尔盖·巴尔巴雷斯', coachStyle:'务实型', formation:'4-4-2',
    playStyle:['身体对抗','中场压迫','定位球'],
    strengths:['身体素质出色','中场硬度'], weaknesses:['创造力不足','锋线火力一般'],
    keyPlayers:[{ name:'皮亚尼奇',pos:'CM',rating:78,status:'fit' },{ name:'科拉希纳茨',pos:'LB',rating:74,status:'fit' }],
    injured:[], suspended:[], squadDepth:5, tournamentExp:3, morale:6, recentForm:['D','W','L','D','W'], fatigue:2,
    tacticalNotes:'波黑以身体对抗和中场硬度著称，皮亚尼奇的组织能力是进攻关键。',
  },
  QAT: {
    coach:'廷丁·马尔克斯', coachStyle:'务实型', formation:'5-3-2',
    playStyle:['铁桶阵','快速反击','技术配合'],
    strengths:['防守组织好','球员技术细腻'], weaknesses:['进攻火力不足','身体对抗弱'],
    keyPlayers:[{ name:'阿费夫',pos:'LW',rating:75,status:'fit' },{ name:'阿里',pos:'ST',rating:73,status:'fit' }],
    injured:[], suspended:[], squadDepth:5, tournamentExp:5, morale:5, recentForm:['L','D','L','W','L'], fatigue:2,
    tacticalNotes:'卡塔尔以防守反击为主，阿费夫的速度和技术是反击利器。',
  },
  SUI: {
    coach:'穆拉特·雅金', coachStyle:'务实型', formation:'3-4-2-1',
    playStyle:['防守反击','中场压迫','定位球'],
    strengths:['防守稳固','团队纪律','大赛稳定'], weaknesses:['进攻火力不足','创造力一般'],
    keyPlayers:[{ name:'扎卡',pos:'CM',rating:82,status:'fit' },{ name:'沙奇里',pos:'RW',rating:78,status:'fit' },{ name:'阿坎吉',pos:'CB',rating:80,status:'fit' }],
    injured:[], suspended:[], squadDepth:7, tournamentExp:7, morale:7, recentForm:['D','W','D','W','W'], fatigue:2,
    tacticalNotes:'雅金的瑞士以防守反击为主，三后卫体系稳固，扎卡是中场核心。',
  },

  // ── C 组 ──
  BRA: {
    coach:'多里瓦尔·儒尼奥尔', coachStyle:'进攻型', formation:'4-3-3',
    playStyle:['技术流','个人突破','短传配合'],
    strengths:['个人能力超强','进攻天赋','大赛基因'], weaknesses:['后防不稳','过度依赖核心球员'],
    keyPlayers:[{ name:'维尼修斯',pos:'LW',rating:92,status:'fit' },{ name:'罗德里戈',pos:'RW',rating:85,status:'fit' },{ name:'恩德里克',pos:'ST',rating:80,status:'fit' },{ name:'马尔基尼奥斯',pos:'CB',rating:86,status:'fit' }],
    injured:[], suspended:[], squadDepth:9, tournamentExp:10, morale:7, recentForm:['W','D','W','L','W'], fatigue:2,
    tacticalNotes:'巴西回归技术流传统，维尼修斯是绝对爆点，但后防线是隐患。',
  },
  MAR: {
    coach:'瓦利德·雷格拉吉', coachStyle:'务实型', formation:'4-1-4-1',
    playStyle:['铁桶阵','快速反击','身体对抗'],
    strengths:['防守纪律极强','反击高效','团队精神'], weaknesses:['进攻创造力依赖个别球员','阵地战乏力'],
    keyPlayers:[{ name:'哈基米',pos:'RB',rating:86,status:'fit' },{ name:'齐耶赫',pos:'RW',rating:80,status:'fit' },{ name:'阿姆拉巴特',pos:'CDM',rating:79,status:'fit' }],
    injured:[], suspended:[], squadDepth:7, tournamentExp:7, morale:8, recentForm:['W','D','W','W','D'], fatigue:2,
    tacticalNotes:'2022年四强黑马延续铁血防守风格，雷格拉吉的低位防守+反击体系非常成熟。',
  },
  HAI: {
    coach:'让-马克·诺维尔', coachStyle:'务实型', formation:'4-4-2',
    playStyle:['身体对抗','快速反击','个人突破'],
    strengths:['身体素质出众','速度型球员'], weaknesses:['战术纪律差','中场控制力弱'],
    keyPlayers:[{ name:'杜塞纳',pos:'ST',rating:72,status:'fit' },{ name:'阿尔西德',pos:'CM',rating:68,status:'fit' }],
    injured:[], suspended:[], squadDepth:4, tournamentExp:2, morale:6, recentForm:['W','L','D','W','L'], fatigue:2,
    tacticalNotes:'海地身体素质出色但战术执行力一般，依赖个人能力创造机会。',
  },
  SCO: {
    coach:'史蒂夫·克拉克', coachStyle:'务实型', formation:'3-5-2',
    playStyle:['身体对抗','中场压迫','定位球'],
    strengths:['防守纪律好','定位球威胁','中场硬度'], weaknesses:['创造力不足','锋线火力一般'],
    keyPlayers:[{ name:'麦克金',pos:'CM',rating:78,status:'fit' },{ name:'罗伯逊',pos:'LWB',rating:80,status:'fit' },{ name:'亚当斯',pos:'ST',rating:74,status:'fit' }],
    injured:[], suspended:[], squadDepth:6, tournamentExp:4, morale:6, recentForm:['D','W','L','D','W'], fatigue:2,
    tacticalNotes:'克拉克的苏格兰以三后卫体系和中场硬度著称，罗伯逊的边路助攻是重要武器。',
  },

  // ── D 组 ──
  USA: {
    coach:'格雷格·贝哈尔特', coachStyle:'务实型', formation:'4-3-3',
    playStyle:['高位逼抢','快速反击','边路进攻'],
    strengths:['主场优势','体能充沛','年轻有冲劲'], weaknesses:['大赛经验不足','中场控制力一般'],
    keyPlayers:[{ name:'普利西奇',pos:'LW',rating:84,status:'fit' },{ name:'麦肯尼',pos:'CM',rating:80,status:'fit' },{ name:'穆萨',pos:'CM',rating:78,status:'fit' },{ name:'雷纳',pos:'AM',rating:79,status:'fit' }],
    injured:[], suspended:[], squadDepth:7, tournamentExp:6, morale:9, recentForm:['W','W','D','W','L'], fatigue:2,
    tacticalNotes:'东道主之一，贝哈尔特倾向务实的4-3-3，强调边路突破和快速反击，主场气氛是最大武器。',
  },
  PAR: {
    coach:'古斯塔沃·阿尔法罗', coachStyle:'务实型', formation:'4-4-2',
    playStyle:['防守反击','身体对抗','中场压迫'],
    strengths:['防守纪律好','中场硬度'], weaknesses:['创造力不足','锋线火力一般'],
    keyPlayers:[{ name:'阿尔米隆',pos:'RW',rating:78,status:'fit' },{ name:'阿尔多·桑切斯',pos:'CM',rating:74,status:'fit' }],
    injured:[], suspended:[], squadDepth:5, tournamentExp:5, morale:5, recentForm:['L','D','W','L','D'], fatigue:2,
    tacticalNotes:'巴拉圭以防守反击为主，中场硬度是特色，但整体实力有限。',
  },
  AUS: {
    coach:'格拉汉姆·阿诺德', coachStyle:'务实型', formation:'4-4-2',
    playStyle:['身体对抗','长传冲吊','高位逼抢'],
    strengths:['体能充沛','团队纪律','定位球'], weaknesses:['技术粗糙','创造力不足'],
    keyPlayers:[{ name:'库奥尔',pos:'ST',rating:74,status:'fit' },{ name:'赫鲁斯蒂奇',pos:'CM',rating:72,status:'fit' }],
    injured:[], suspended:[], squadDepth:5, tournamentExp:5, morale:6, recentForm:['L','D','W','L','D'], fatigue:2,
    tacticalNotes:'典型的英式打法，强调身体和跑动，面对技术型球队会很吃亏。',
  },
  TUR: {
    coach:'文森佐·蒙特拉', coachStyle:'进攻型', formation:'4-2-3-1',
    playStyle:['高位压迫','控球型','快速传递'],
    strengths:['中场创造力','年轻有活力','技术出色'], weaknesses:['防守不稳','大赛经验不足'],
    keyPlayers:[{ name:'恰尔汗奥卢',pos:'AM',rating:84,status:'fit' },{ name:'于纳尔',pos:'ST',rating:76,status:'fit' },{ name:'德米拉尔',pos:'CB',rating:78,status:'fit' }],
    injured:[], suspended:[], squadDepth:7, tournamentExp:5, morale:7, recentForm:['W','W','D','L','W'], fatigue:2,
    tacticalNotes:'蒙特拉执教后土耳其踢得更具攻击性，恰尔汗奥卢是中场发动机，年轻球员充满冲劲。',
  },

  // ── E 组 ──
  GER: {
    coach:'尤利安·纳格尔斯曼', coachStyle:'进攻型', formation:'4-2-3-1',
    playStyle:['高位压迫','控球型','快速传递'],
    strengths:['战术素养高','中场厚度','年轻有冲劲'], weaknesses:['锋线终结力不稳','后防偶有失误'],
    keyPlayers:[{ name:'穆西亚拉',pos:'AM',rating:87,status:'fit' },{ name:'维尔茨',pos:'AM',rating:86,status:'fit' },{ name:'吕迪格',pos:'CB',rating:84,status:'fit' }],
    injured:[], suspended:[], squadDepth:9, tournamentExp:8, morale:7, recentForm:['W','W','D','W','W'], fatigue:2,
    tacticalNotes:'纳格尔斯曼执教后德国焕然一新，穆西亚拉+维尔茨双核极具创造力。',
  },
  CUW: {
    coach:'雷米·维克托', coachStyle:'务实型', formation:'4-4-2',
    playStyle:['身体对抗','快速反击','边路进攻'],
    strengths:['身体素质出色','团队精神'], weaknesses:['技术水平差距大','战术执行力不足'],
    keyPlayers:[{ name:'巴库纳',pos:'CM',rating:70,status:'fit' },{ name:'霍伊',pos:'ST',rating:68,status:'fit' }],
    injured:[], suspended:[], squadDepth:3, tournamentExp:1, morale:7, recentForm:['W','W','D','L','W'], fatigue:2,
    tacticalNotes:'库拉索首次参加世界杯，以身体对抗和团队精神为主要武器。',
  },
  CIV: {
    coach:'让-路易斯·加塞特', coachStyle:'平衡型', formation:'4-3-3',
    playStyle:['身体对抗','快速反击','技术流'],
    strengths:['身体素质出众','技术出色','大赛经验'], weaknesses:['战术纪律差','中场控制力不稳定'],
    keyPlayers:[{ name:'凯西耶',pos:'CM',rating:80,status:'fit' },{ name:'哈勒尔',pos:'ST',rating:76,status:'fit' },{ name:'佩佩',pos:'RW',rating:74,status:'fit' }],
    injured:[], suspended:[], squadDepth:6, tournamentExp:5, morale:6, recentForm:['W','D','W','L','W'], fatigue:2,
    tacticalNotes:'科特迪瓦身体素质出色，技术也不错，但战术执行力是短板。',
  },
  ECU: {
    coach:'费利克斯·桑切斯', coachStyle:'控球型', formation:'4-3-3',
    playStyle:['控球型','高位压迫','快速传递'],
    strengths:['中场控制力强','技术出色','团队配合'], weaknesses:['锋线终结力一般','身体对抗不足'],
    keyPlayers:[{ name:'凯塞多',pos:'CM',rating:82,status:'fit' },{ name:'瓦伦西亚',pos:'ST',rating:76,status:'fit' },{ name:'埃斯图皮尼安',pos:'LB',rating:78,status:'fit' }],
    injured:[], suspended:[], squadDepth:6, tournamentExp:4, morale:7, recentForm:['W','D','W','W','L'], fatigue:2,
    tacticalNotes:'桑切斯的厄瓜多尔以控球和高位压迫为核心，凯塞多是中场绝对核心。',
  },

  // ── F 组 ──
  NED: {
    coach:'罗纳德·科曼', coachStyle:'平衡型', formation:'3-4-1-2',
    playStyle:['全攻全守','高位压迫','边翼卫进攻'],
    strengths:['战术灵活','中场厚度','全攻全守传统'], weaknesses:['锋线终结力不稳','三后卫体系风险'],
    keyPlayers:[{ name:'德容',pos:'CM',rating:85,status:'fit' },{ name:'加克波',pos:'LW',rating:82,status:'fit' },{ name:'德里赫特',pos:'CB',rating:83,status:'fit' }],
    injured:[], suspended:[], squadDepth:8, tournamentExp:8, morale:7, recentForm:['W','W','D','W','L'], fatigue:2,
    tacticalNotes:'科曼的荷兰延续全攻全守传统，三后卫体系攻守转换快，但锋线缺顶级射手。',
  },
  JPN: {
    coach:'森保一', coachStyle:'务实型', formation:'4-2-3-1',
    playStyle:['高位逼抢','快速传递','团队配合'],
    strengths:['战术执行力强','体能充沛','团队纪律'], weaknesses:['身体对抗不足','高空球劣势'],
    keyPlayers:[{ name:'久保建英',pos:'RW',rating:82,status:'fit' },{ name:'三笘薫',pos:'LW',rating:81,status:'fit' },{ name:'远藤航',pos:'CDM',rating:80,status:'fit' }],
    injured:[], suspended:[], squadDepth:7, tournamentExp:7, morale:7, recentForm:['W','D','W','W','L'], fatigue:2,
    tacticalNotes:'森保一的日本以高位逼抢和快速传递著称，整体移动能力极强。',
  },
  SWE: {
    coach:'乔恩·达尔·托马森', coachStyle:'务实型', formation:'4-4-2',
    playStyle:['身体对抗','防守反击','定位球'],
    strengths:['身体素质出色','防守纪律好','定位球威胁'], weaknesses:['创造力不足','技术粗糙'],
    keyPlayers:[{ name:'库卢塞夫斯基',pos:'RW',rating:82,status:'fit' },{ name:'伊萨克',pos:'ST',rating:80,status:'fit' },{ name:'林德洛夫',pos:'CB',rating:78,status:'fit' }],
    injured:[], suspended:[], squadDepth:6, tournamentExp:6, morale:6, recentForm:['D','W','L','W','D'], fatigue:2,
    tacticalNotes:'瑞典以身体对抗和防守纪律著称，库卢塞夫斯基和伊萨克的锋线组合有威胁。',
  },
  TUN: {
    coach:'卡德里', coachStyle:'务实型', formation:'4-3-3',
    playStyle:['身体对抗','快速反击','中场压迫'],
    strengths:['防守纪律好','中场硬度'], weaknesses:['创造力不足','锋线火力一般'],
    keyPlayers:[{ name:'姆萨克尼',pos:'LW',rating:76,status:'fit' },{ name:'斯希里',pos:'CM',rating:74,status:'fit' }],
    injured:[], suspended:[], squadDepth:5, tournamentExp:6, morale:6, recentForm:['D','L','W','D','W'], fatigue:2,
    tacticalNotes:'突尼斯以防守纪律和中场硬度著称，但整体实力有限。',
  },

  // ── G 组 ──
  BEL: {
    coach:'多梅尼科·特德斯科', coachStyle:'平衡型', formation:'3-4-2-1',
    playStyle:['控球型','中场控制','快速传递'],
    strengths:['中场创造力','经验丰富'], weaknesses:['黄金一代老化','后防不稳'],
    keyPlayers:[{ name:'德布劳内',pos:'AM',rating:88,status:'fit' },{ name:'卢卡库',pos:'ST',rating:82,status:'fit' },{ name:'库尔图瓦',pos:'GK',rating:88,status:'fit' }],
    injured:[], suspended:[], squadDepth:7, tournamentExp:7, morale:6, recentForm:['D','W','L','W','D'], fatigue:2,
    tacticalNotes:'黄金一代最后的世界杯，德布劳内仍是世界级，但整体老化是最大问题。',
  },
  EGY: {
    coach:'霍萨姆·哈桑', coachStyle:'务实型', formation:'4-2-3-1',
    playStyle:['防守反击','边路进攻','个人突破'],
    strengths:['萨拉赫领衔','技术出色'], weaknesses:['过度依赖萨拉赫','中场控制力一般'],
    keyPlayers:[{ name:'萨拉赫',pos:'RW',rating:87,status:'fit' },{ name:'埃尔内尼',pos:'CM',rating:74,status:'fit' }],
    injured:[], suspended:[], squadDepth:5, tournamentExp:5, morale:6, recentForm:['W','D','L','W','D'], fatigue:2,
    tacticalNotes:'埃及几乎等于萨拉赫一人球队，防守端靠组织，进攻端靠萨拉赫个人能力。',
  },
  IRN: {
    coach:'阿米尔·加莱诺伊', coachStyle:'务实型', formation:'4-4-2',
    playStyle:['铁桶阵','快速反击','身体对抗'],
    strengths:['防守纪律极强','反击高效'], weaknesses:['创造力不足','进攻手段单一'],
    keyPlayers:[{ name:'阿兹蒙',pos:'ST',rating:76,status:'fit' },{ name:'塔雷米',pos:'ST',rating:78,status:'fit' },{ name:'贾汉巴赫什',pos:'RW',rating:74,status:'fit' }],
    injured:[], suspended:[], squadDepth:5, tournamentExp:5, morale:6, recentForm:['D','W','L','D','W'], fatigue:2,
    tacticalNotes:'伊朗以铁桶阵和反击著称，塔雷米+阿兹蒙双前锋组合有威胁。',
  },
  NZL: {
    coach:'达伦·贝泽利', coachStyle:'防守型', formation:'5-4-1',
    playStyle:['铁桶阵','长传反击','定位球'],
    strengths:['防守纪律好','定位球威胁'], weaknesses:['个人能力差距大','进攻手段单一'],
    keyPlayers:[{ name:'伍德',pos:'ST',rating:72,status:'fit' },{ name:'辛格',pos:'CM',rating:68,status:'fit' }],
    injured:[], suspended:[], squadDepth:4, tournamentExp:3, morale:5, recentForm:['L','D','L','W','L'], fatigue:2,
    tacticalNotes:'实力最弱档，会摆大巴寻求0-0或偷袭，定位球是主要得分手段。',
  },

  // ── H 组 ──
  ESP: {
    coach:'路易斯·德拉富恩特', coachStyle:'进攻型', formation:'4-3-3',
    playStyle:['tiki-taka','高位压迫','控球型'],
    strengths:['中场控制力极强','年轻有活力','欧洲杯冠军'], weaknesses:['锋线终结力一般','面对铁桶阵效率低'],
    keyPlayers:[{ name:'亚马尔',pos:'RW',rating:86,status:'fit' },{ name:'佩德里',pos:'CM',rating:87,status:'fit' },{ name:'罗德里',pos:'CDM',rating:91,status:'fit' }],
    injured:[], suspended:[], squadDepth:9, tournamentExp:8, morale:9, recentForm:['W','W','W','W','D'], fatigue:2,
    tacticalNotes:'欧洲杯冠军延续tiki-taka传统，亚马尔+佩德里+罗德里中场铁三角统治力极强。',
  },
  CPV: {
    coach:'佩德罗·布里斯托', coachStyle:'务实型', formation:'4-4-2',
    playStyle:['身体对抗','快速反击','中场压迫'],
    strengths:['身体素质出色','团队精神'], weaknesses:['技术水平差距大','战术执行力不足'],
    keyPlayers:[{ name:'门德斯',pos:'CM',rating:70,status:'fit' },{ name:'罗德里格斯',pos:'ST',rating:68,status:'fit' }],
    injured:[], suspended:[], squadDepth:3, tournamentExp:1, morale:7, recentForm:['W','W','D','L','W'], fatigue:2,
    tacticalNotes:'佛得角首次参加世界杯，以身体对抗和团队精神为主要武器。',
  },
  KSA: {
    coach:'埃尔韦·勒纳尔', coachStyle:'防守型', formation:'4-5-1',
    playStyle:['铁桶阵','快速反击','技术配合'],
    strengths:['防守组织好','球员技术细腻'], weaknesses:['进攻火力不足','身体对抗弱'],
    keyPlayers:[{ name:'达瓦萨里',pos:'RW',rating:74,status:'fit' },{ name:'卡努',pos:'CDM',rating:72,status:'fit' }],
    injured:[], suspended:[], squadDepth:5, tournamentExp:5, morale:5, recentForm:['D','L','W','D','L'], fatigue:2,
    tacticalNotes:'勒纳尔擅长打造防守体系，2022年曾爆冷击败阿根廷，但整体实力有限。',
  },
  URU: {
    coach:'马塞洛·贝尔萨', coachStyle:'进攻型', formation:'4-3-3',
    playStyle:['高位逼抢','疯狂跑动','快速传递'],
    strengths:['逼抢强度极高','团队跑动','前锋线年轻有活力'], weaknesses:['体能消耗大','后防空当'],
    keyPlayers:[{ name:'努涅斯',pos:'ST',rating:82,status:'fit' },{ name:'巴尔韦德',pos:'CM',rating:86,status:'fit' },{ name:'阿劳霍',pos:'CB',rating:82,status:'fit' }],
    injured:[], suspended:[], squadDepth:7, tournamentExp:7, morale:7, recentForm:['W','W','D','W','L'], fatigue:2,
    tacticalNotes:'疯子贝尔萨的乌拉圭踢法极具侵略性，全场逼抢+疯狂跑动，但体能消耗巨大。',
  },

  // ── I 组 ──
  FRA: {
    coach:'迪迪埃·德尚', coachStyle:'务实型', formation:'4-2-3-1',
    playStyle:['快速反击','边路突破','高位压迫'],
    strengths:['阵容厚度最深','个人能力顶级','大赛基因'], weaknesses:['内部团结问题','创造力依赖核心'],
    keyPlayers:[{ name:'姆巴佩',pos:'LW',rating:93,status:'fit' },{ name:'登贝莱',pos:'RW',rating:86,status:'fit' },{ name:'格列兹曼',pos:'AM',rating:85,status:'fit' },{ name:'萨利巴',pos:'CB',rating:86,status:'fit' }],
    injured:[], suspended:[], squadDepth:10, tournamentExp:9, morale:8, recentForm:['W','W','D','W','W'], fatigue:2,
    tacticalNotes:'德尚的法国以实用主义著称，姆巴佩的速度是核武器，防守端萨利巴世界级。',
  },
  SEN: {
    coach:'阿利乌·西塞', coachStyle:'务实型', formation:'4-3-3',
    playStyle:['身体对抗','快速反击','高位逼抢'],
    strengths:['身体素质出众','反击速度快','非洲杯冠军底蕴'], weaknesses:['阵地战创造力不足','定位球防守一般'],
    keyPlayers:[{ name:'马内',pos:'LW',rating:82,status:'fit' },{ name:'库利巴利',pos:'CB',rating:80,status:'fit' },{ name:'盖耶',pos:'CM',rating:78,status:'fit' }],
    injured:[], suspended:[], squadDepth:6, tournamentExp:6, morale:7, recentForm:['W','W','D','L','W'], fatigue:2,
    tacticalNotes:'西塞打造的塞内加尔以纪律性和身体对抗著称，擅长低位防守后快速反击。',
  },
  IRQ: {
    coach:'赫苏斯·卡萨斯', coachStyle:'务实型', formation:'4-4-2',
    playStyle:['防守反击','中场压迫','身体对抗'],
    strengths:['防守纪律好','中场硬度'], weaknesses:['创造力不足','锋线火力一般'],
    keyPlayers:[{ name:'阿里',pos:'ST',rating:74,status:'fit' },{ name:'阿德南',pos:'LB',rating:72,status:'fit' }],
    injured:[], suspended:[], squadDepth:5, tournamentExp:3, morale:6, recentForm:['W','D','L','W','D'], fatigue:2,
    tacticalNotes:'伊拉克以防守纪律和中场硬度著称，但整体实力有限。',
  },
  NOR: {
    coach:'斯托勒·索尔巴肯', coachStyle:'平衡型', formation:'4-3-3',
    playStyle:['高位压迫','快速传递','身体对抗'],
    strengths:['身体素质出色','中场创造力'], weaknesses:['锋线终结力不稳定','大赛经验不足'],
    keyPlayers:[{ name:'哈兰德',pos:'ST',rating:91,status:'fit' },{ name:'厄德高',pos:'AM',rating:86,status:'fit' },{ name:'索尔洛特',pos:'ST',rating:78,status:'fit' }],
    injured:[], suspended:[], squadDepth:7, tournamentExp:4, morale:7, recentForm:['W','D','W','L','W'], fatigue:2,
    tacticalNotes:'挪威拥有哈兰德+厄德高双核，个人能力顶级但整体配合有待提升。',
  },

  // ── J 组 ──
  ARG: {
    coach:'利昂内尔·斯卡洛尼', coachStyle:'平衡型', formation:'4-3-3',
    playStyle:['控球型','高位压迫','快速传递'],
    strengths:['团队凝聚力','卫冕冠军底蕴','中场铁三角'], weaknesses:['核心老化','替补与主力差距'],
    keyPlayers:[{ name:'梅西',pos:'RW',rating:90,status:'fit' },{ name:'阿尔瓦雷斯',pos:'ST',rating:84,status:'fit' },{ name:'恩佐·费尔南德斯',pos:'CM',rating:84,status:'fit' }],
    injured:[], suspended:[], squadDepth:8, tournamentExp:10, morale:9, recentForm:['W','W','W','D','W'], fatigue:2,
    tacticalNotes:'卫冕冠军，斯卡洛尼体系成熟，梅西虽老但仍是核心，中场铁三角恩佐+麦卡+德保罗极具统治力。',
  },
  ALG: {
    coach:'佩特科维奇', coachStyle:'务实型', formation:'4-3-3',
    playStyle:['身体对抗','快速反击','边路进攻'],
    strengths:['身体素质出色','速度型球员'], weaknesses:['战术纪律差','中场控制力不稳定'],
    keyPlayers:[{ name:'马赫雷斯',pos:'RW',rating:80,status:'fit' },{ name:'本纳赛尔',pos:'CM',rating:76,status:'fit' }],
    injured:[], suspended:[], squadDepth:5, tournamentExp:4, morale:6, recentForm:['W','D','L','W','D'], fatigue:2,
    tacticalNotes:'阿尔及利亚以身体对抗和速度见长，马赫雷斯的个人能力是进攻关键。',
  },
  AUT: {
    coach:'拉尔夫·朗尼克', coachStyle:'进攻型', formation:'4-3-3',
    playStyle:['高位逼抢','疯狂跑动','快速传递'],
    strengths:['逼抢强度极高','体能充沛','战术纪律'], weaknesses:['创造力依赖核心','锋线火力一般'],
    keyPlayers:[{ name:'萨比策',pos:'CM',rating:80,status:'fit' },{ name:'阿拉巴',pos:'CB',rating:82,status:'fit' },{ name:'鲍姆加特纳',pos:'AM',rating:78,status:'fit' }],
    injured:[], suspended:[], squadDepth:7, tournamentExp:5, morale:7, recentForm:['W','W','D','W','L'], fatigue:2,
    tacticalNotes:'朗尼克的奥地利以高位逼抢和疯狂跑动著称，战术执行力极强。',
  },
  JOR: {
    coach:'胡辛·阿穆塔', coachStyle:'务实型', formation:'4-4-2',
    playStyle:['防守反击','身体对抗','中场压迫'],
    strengths:['防守纪律好','团队精神'], weaknesses:['创造力不足','技术水平有限'],
    keyPlayers:[{ name:'阿尔塔马里',pos:'ST',rating:72,status:'fit' },{ name:'阿尔纳伊马特',pos:'CM',rating:70,status:'fit' }],
    injured:[], suspended:[], squadDepth:4, tournamentExp:2, morale:6, recentForm:['W','D','L','W','D'], fatigue:2,
    tacticalNotes:'约旦以防守纪律和团队精神著称，但整体实力有限。',
  },

  // ── K 组 ──
  POR: {
    coach:'罗伯托·马丁内斯', coachStyle:'进攻型', formation:'4-3-3',
    playStyle:['控球型','边路进攻','高位压迫'],
    strengths:['个人能力顶级','阵容厚度深'], weaknesses:['C罗老化','防守端偶有松懈'],
    keyPlayers:[{ name:'C罗',pos:'ST',rating:82,status:'fit' },{ name:'贝尔纳多·席尔瓦',pos:'RW',rating:87,status:'fit' },{ name:'布鲁诺·费尔南德斯',pos:'AM',rating:86,status:'fit' }],
    injured:[], suspended:[], squadDepth:9, tournamentExp:8, morale:7, recentForm:['W','D','W','W','W'], fatigue:2,
    tacticalNotes:'马丁内斯让葡萄牙踢得更流畅，B·席尔瓦+B费创造力爆表，C罗可能是最后一届。',
  },
  COD: {
    coach:'塞巴斯蒂安·德萨布尔', coachStyle:'务实型', formation:'4-3-3',
    playStyle:['身体对抗','快速反击','边路进攻'],
    strengths:['身体素质出众','速度型球员'], weaknesses:['战术纪律差','中场控制力弱'],
    keyPlayers:[{ name:'巴坎布',pos:'ST',rating:76,status:'fit' },{ name:'穆图萨米',pos:'CM',rating:72,status:'fit' }],
    injured:[], suspended:[], squadDepth:5, tournamentExp:3, morale:6, recentForm:['W','L','D','W','L'], fatigue:2,
    tacticalNotes:'刚果民主以身体对抗和速度见长，但战术执行力是短板。',
  },
  UZB: {
    coach:'卡塔尼奇', coachStyle:'务实型', formation:'4-4-2',
    playStyle:['防守反击','中场压迫','技术配合'],
    strengths:['防守纪律好','中场硬度'], weaknesses:['创造力不足','锋线火力一般'],
    keyPlayers:[{ name:'绍穆罗多夫',pos:'ST',rating:74,status:'fit' },{ name:'哈姆达莫夫',pos:'CM',rating:72,status:'fit' }],
    injured:[], suspended:[], squadDepth:5, tournamentExp:2, morale:6, recentForm:['D','W','L','W','D'], fatigue:2,
    tacticalNotes:'乌兹别克斯坦首次参加世界杯，以防守纪律和中场硬度著称。',
  },
  COL: {
    coach:'内斯托·洛伦佐', coachStyle:'平衡型', formation:'4-2-3-1',
    playStyle:['控球型','中场压迫','技术流'],
    strengths:['中场技术出色','大赛经验丰富','团队配合默契'], weaknesses:['锋线效率不稳','后防空当较大'],
    keyPlayers:[{ name:'迪亚斯',pos:'LW',rating:84,status:'fit' },{ name:'哈梅斯',pos:'AM',rating:80,status:'fit' },{ name:'穆里尔',pos:'ST',rating:79,status:'fit' }],
    injured:[], suspended:[], squadDepth:7, tournamentExp:7, morale:7, recentForm:['W','D','W','W','D'], fatigue:2,
    tacticalNotes:'洛伦佐延续哥伦比亚技术流传统，中场控制力强，哈梅斯的创造力是关键。',
  },

  // ── L 组 ──
  ENG: {
    coach:'加雷斯·索斯盖特', coachStyle:'平衡型', formation:'4-2-3-1',
    playStyle:['控球型','高位压迫','边路进攻'],
    strengths:['阵容厚度深','大赛经验丰富','定位球出色'], weaknesses:['关键时刻心态不稳','创造力依赖个别球员'],
    keyPlayers:[{ name:'贝林厄姆',pos:'AM',rating:90,status:'fit' },{ name:'萨卡',pos:'RW',rating:88,status:'fit' },{ name:'凯恩',pos:'ST',rating:89,status:'fit' }],
    injured:[], suspended:[], squadDepth:9, tournamentExp:8, morale:8, recentForm:['W','W','W','D','W'], fatigue:2,
    tacticalNotes:'索斯盖特倾向稳扎稳打，贝林厄姆是绝对核心，两翼萨卡+福登极具威胁。',
  },
  CRO: {
    coach:'兹拉科·达利奇', coachStyle:'平衡型', formation:'4-3-3',
    playStyle:['中场控制','耐心传导','经验取胜'],
    strengths:['中场大师级','大赛经验极丰富','韧性十足'], weaknesses:['核心老化严重','锋线终结力不足'],
    keyPlayers:[{ name:'莫德里奇',pos:'CM',rating:84,status:'fit' },{ name:'科瓦契奇',pos:'CM',rating:80,status:'fit' },{ name:'格瓦迪奥尔',pos:'CB',rating:84,status:'fit' }],
    injured:[], suspended:[], squadDepth:6, tournamentExp:9, morale:7, recentForm:['D','W','L','W','D'], fatigue:2,
    tacticalNotes:'莫德里奇可能最后一届，克罗地亚中场仍是世界级，但体能和锋线是问题。',
  },
  GHA: {
    coach:'克里斯·休顿', coachStyle:'务实型', formation:'4-3-3',
    playStyle:['身体对抗','快速反击','中场压迫'],
    strengths:['身体素质出众','中场硬度'], weaknesses:['战术纪律差','创造力不足'],
    keyPlayers:[{ name:'阿尤',pos:'LW',rating:74,status:'fit' },{ name:'帕蒂',pos:'CM',rating:76,status:'fit' }],
    injured:[], suspended:[], squadDepth:5, tournamentExp:5, morale:6, recentForm:['L','D','W','L','W'], fatigue:2,
    tacticalNotes:'加纳以身体对抗和中场硬度著称，但整体实力有限。',
  },
  PAN: {
    coach:'托马斯·克里斯蒂安森', coachStyle:'务实型', formation:'4-4-2',
    playStyle:['防守反击','身体对抗','中场压迫'],
    strengths:['防守纪律好','团队精神'], weaknesses:['创造力不足','技术水平有限'],
    keyPlayers:[{ name:'巴尔塞纳斯',pos:'RW',rating:72,status:'fit' },{ name:'戈多伊',pos:'CM',rating:70,status:'fit' }],
    injured:[], suspended:[], squadDepth:4, tournamentExp:3, morale:5, recentForm:['L','D','W','L','D'], fatigue:2,
    tacticalNotes:'巴拿马以防守纪律和团队精神著称，但整体实力有限。',
  },
};

const PROFILED_TEAMS = Object.keys(TeamProfiles);
